---
on: [push, pull_request]
name: default

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install neovim

      - name: Check out required packages
        run: |
          mkdir packages
          git clone https://github.com/nvim-lua/plenary.nvim.git packages/plenary.nvim
          git clone git@github.com:nvim-tree/nvim-web-devicons.git packages/nvim-web-devicons

      - name: Run test
        run: make

  lint:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: |
              sudo apt-get update
              sudo apt-get install luarocks
              sudo luarocks install luacheck

        - name: Run lint
          run: make lint
