---
on: [push, pull_request]
name: default

jobs:
  tests:
    name: tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: MilesChou/lua-action@v0.0.1
      - uses: JohnnyMorganz/stylua-action@v2
